-- Seed file for Delta State University (DELSU) Departments
BEGIN;

WITH inst AS (
    SELECT id FROM academic.institutions WHERE name = 'Delta State University' LIMIT 1
)
INSERT INTO academic.departments (name, institution_id)
SELECT d.name, inst.id
FROM inst, (VALUES
    ('Accounting'),
    ('Agricultural Economics'),
    ('Agricultural Science and Education'),
    ('Agriculture'),
    ('Anatomy'),
    ('Animal Science'),
    ('Banking and Finance'),
    ('Biochemistry'),
    ('Botany'),
    ('Business Administration'),
    ('Business Education'),
    ('Chemical Engineering'),
    ('Chemistry'),
    ('Civil Engineering'),
    ('Computer Science'),
    ('Drama / Dramatic / Performing Arts'),
    ('Economics'),
    ('Education and Biology'),
    ('Education and Chemistry'),
    ('Education and Computer Science'),
    ('Education and Economics'),
    ('Education and English Language'),
    ('Education Fine and Applied Arts'),
    ('Education and French'),
    ('Education and Geography'),
    ('Education and History'),
    ('Education and Integrated Science'),
    ('Education and Mathematics'),
    ('Education and Music'),
    ('Education and Physics'),
    ('Education and Political Science'),
    ('Education and Religious Studies'),
    ('Education and Social Studies'),
    ('Educational Management'),
    ('Electrical / Electronics Engineering'),
    ('English and Literary Studies'),
    ('Fine Art / Fine and Applied Arts'),
    ('Fisheries'),
    ('Forestry And WildLife'),
    ('French'),
    ('Geography and Regional Planning'),
    ('Geology'),
    ('Guidance and Counseling'),
    ('Health Education'),
    ('History and International Studies'),
    ('Home Economics and Education'),
    ('Industrial Chemistry'),
    ('Industrial Mathematics'),
    ('Law'),
    ('Library and Information Science'),
    ('Linguistics'),
    ('Linguistic / Urhobo'),
    ('Marketing'),
    ('Mass Communication'),
    ('Mathematics'),
    ('Mechanical and Metallurgical Engineering'),
    ('Mechanical Engineering'),
    ('Medical Biochemistry'),
    ('Medicine and Surgery'),
    ('Microbiology'),
    ('Music'),
    ('Nursery and Primary Education'),
    ('Nursing / Nursing Science'),
    ('Petroleum Engineering'),
    ('Pharmacology And Therapeutics'),
    ('Pharmacy'),
    ('Philosophy'),
    ('Physical Education'),
    ('Physics'),
    ('Physiology'),
    ('Political Science'),
    ('Psychology'),
    ('Religious Studies'),
    ('Science Laboratory Technology'),
    ('Sociology'),
    ('Soil Science'),
    ('Teacher Education Science'),
    ('Technical Education'),
    ('Theatre Arts'),
    ('Zoology')
) AS d(name)
ON CONFLICT (name, institution_id) DO NOTHING;

COMMIT;
