-- ============================================
-- ADD MORE NIGERIAN INSTITUTIONS MIGRATION
-- ============================================
-- Adding a comprehensive list of Nigerian universities, polytechnics, and colleges

INSERT INTO academic.institutions (name, location) VALUES
  ('University of Ilorin', 'Ilorin, Kwara State'),
  ('University of Port Harcourt', 'Port Harcourt, Rivers State'),
  ('Nnamdi Azikiwe University', 'Awka, Anambra State'),
  ('University of Abuja', 'Abuja, FCT'),
  ('Federal University of Technology, Minna', 'Minna, Niger State'),
  ('Federal University of Technology, Owerri', 'Owerri, Imo State'),
  ('Bayero University Kano', 'Kano, Kano State'),
  ('University of Calabar', 'Calabar, Cross River State'),
  ('University of Uyo', 'Uyo, Akwa Ibom State'),
  ('University of Jos', 'Jos, Plateau State'),
  ('Ekiti State University', 'Ado-Ekiti, Ekiti State'),
  ('Ladoke Akintola University of Technology', 'Ogbomoso, Oyo State'),
  ('Delta State University', 'Abraka, Delta State'),
  ('Rivers State University', 'Port Harcourt, Rivers State'),
  ('Kaduna State University', 'Kaduna, Kaduna State'),
  ('Osun State University', 'Osogbo, Osun State'),
  ('Ambrose Alli University', 'Ekpoma, Edo State'),
  ('Babcock University', 'Ilishan-Remo, Ogun State'),
  ('Afe Babalola University', 'Ado-Ekiti, Ekiti State'),
  ('Bowen University', 'Iwo, Osun State'),
  ('Bells University of Technology', 'Ota, Ogun State'),
  ('University of Maiduguri', 'Maiduguri, Borno State'),
  ('Usmanu Danfodiyo University', 'Sokoto, Sokoto State'),
  ('Federal University, Oye-Ekiti', 'Oye-Ekiti, Ekiti State'),
  ('Kwara State University', 'Malete, Kwara State'),
  ('Adekunle Ajasin University', 'Akungba-Akoko, Ondo State'),
  ('Lagos State Polytechnic', 'Ikorodu, Lagos State'),
  ('Yaba College of Technology', 'Yaba, Lagos State'),
  ('Federal Polytechnic, Ilaro', 'Ilaro, Ogun State'),
  ('Federal Polytechnic, Nekede', 'Nekede, Imo State'),
  ('Akanu Ibiam Federal Polytechnic', 'Unwana, Ebonyi State'),
  ('Auchi Polytechnic', 'Auchi, Edo State'),
  ('Federal University of Agriculture, Abeokuta', 'Abeokuta, Ogun State'),
  ('Michael Okpara University of Agriculture', 'Umudike, Abia State'),
  ('Joseph Ayo Babalola University', 'Ikeji-Arakeji, Osun State'),
  ('Bingham University', 'Karu, Nasarawa State'),
  ('Crawford University', 'Igbesa, Ogun State'),
  ('Redeemer''s University', 'Ede, Osun State'),
  ('Lead City University', 'Ibadan, Oyo State'),
  ('Pan-Atlantic University', 'Ibeju-Lekki, Lagos State'),
  ('Igbinedion University', 'Okada, Edo State'),
  ('Madonna University', 'Elele, Rivers State'),
  ('Nile University of Nigeria', 'Abuja, FCT'),
  ('Baze University', 'Abuja, FCT'),
  ('American University of Nigeria', 'Yola, Adamawa State'),
  ('Federal University, Lokoja', 'Lokoja, Kogi State'),
  ('Federal University, Lafia', 'Lafia, Nasarawa State'),
  ('Federal University, Kashere', 'Kashere, Gombe State'),
  ('Federal University, Wukari', 'Wukari, Taraba State'),
  ('Federal University, Dutsin-Ma', 'Dutsin-Ma, Katsina State'),
  ('Federal University, Dutse', 'Dutse, Jigawa State'),
  ('Federal University, Ndufu-Alike', 'Ikwo, Ebonyi State'),
  ('Federal University, Otuoke', 'Otuoke, Bayelsa State'),
  ('Ignatius Ajuru University of Education', 'Port Harcourt, Rivers State'),
  ('National Open University of Nigeria', 'Abuja, FCT')
ON CONFLICT (name) DO NOTHING;
